import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const inputPath = path.join(__dirname, 'preload.ts');
const outputPath = path.join(__dirname, 'preload.cjs');

const source = await fs.readFile(inputPath, 'utf8');
const transpiled = ts.transpileModule(source, {
  compilerOptions: {
    target: ts.ScriptTarget.ES2020,
    module: ts.ModuleKind.CommonJS,
    moduleResolution: ts.ModuleResolutionKind.Node10,
    esModuleInterop: true,
  },
  fileName: inputPath,
  reportDiagnostics: true,
});

const diagnostics = transpiled.diagnostics ?? [];
const hasErrors = diagnostics.some(
  (diagnostic) => diagnostic.category === ts.DiagnosticCategory.Error
);

if (diagnostics.length > 0) {
  const formatHost = {
    getCanonicalFileName: (fileName) => fileName,
    getCurrentDirectory: () => process.cwd(),
    getNewLine: () => '\n',
  };

  const formatted = ts.formatDiagnosticsWithColorAndContext(
    diagnostics,
    formatHost
  );

  if (hasErrors) {
    throw new Error(formatted);
  }

  process.stderr.write(formatted);
}

const generated = `// Generated from electron/preload.ts. Do not edit this file directly.\n${transpiled.outputText}`;
await fs.writeFile(outputPath, generated);
