// Generated from electron/preload.ts. Do not edit this file directly.
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const electron_1 = require("electron");
const bridge = {
    // ── Screen Capture (on-demand, hides overlay first) ─────────────────────────
    captureScreenshot: () => electron_1.ipcRenderer.invoke('capture-screenshot'),
    captureScreenshotJpeg: (quality) => electron_1.ipcRenderer.invoke('capture-screenshot-jpeg', quality),
    captureRegion: (x, y, w, h, viewportWidth, viewportHeight) => electron_1.ipcRenderer.invoke('capture-region', x, y, w, h, viewportWidth, viewportHeight),
    getDesktopSources: () => electron_1.ipcRenderer.invoke('get-desktop-sources'),
    getRuntimeProfile: () => electron_1.ipcRenderer.invoke('get-runtime-profile'),
    // ── Global Escape Hotkey ────────────────────────────────────────────────────
    onGlobalEscape: (cb) => {
        const listener = () => cb();
        electron_1.ipcRenderer.on('global-escape', listener);
        return () => electron_1.ipcRenderer.removeListener('global-escape', listener);
    },
    // ── Window Controls ─────────────────────────────────────────────────────────
    setAlwaysOnTop: (value) => electron_1.ipcRenderer.invoke('set-always-on-top', value),
    setIgnoreMouseEvents: (ignore, opts) => electron_1.ipcRenderer.invoke('set-ignore-mouse-events', ignore, opts),
    // ── Platform Info ───────────────────────────────────────────────────────────
    platform: process.platform,
    // ── Microphone permission (main process, persists under bundle ID) ──────────
    requestMicPermission: () => electron_1.ipcRenderer.invoke('request-mic-permission'),
    // ── App relaunch (used after granting permissions) ──────────────────────────
    relaunch: () => electron_1.ipcRenderer.invoke('relaunch'),
    // ── Runtime detection ───────────────────────────────────────────────────────
    isElectron: true,
    // ── Agent Tools ────────────────────────────────────────────────────────────
    agent: {
        runAppleScript: (script) => electron_1.ipcRenderer.invoke('agent:run-applescript', script),
        openUrl: (url) => electron_1.ipcRenderer.invoke('agent:open-url', url),
        getFrontmostApp: () => electron_1.ipcRenderer.invoke('agent:get-frontmost-app'),
        openApp: (appName) => electron_1.ipcRenderer.invoke('agent:open-app', appName),
        typeText: (text) => electron_1.ipcRenderer.invoke('agent:type-text', text),
        pressKeys: (keys) => electron_1.ipcRenderer.invoke('agent:press-keys', keys),
        shellExec: (command, timeoutMs) => electron_1.ipcRenderer.invoke('agent:shell-exec', command, timeoutMs),
        webSearch: (query) => electron_1.ipcRenderer.invoke('agent:web-search', query),
        cancel: () => electron_1.ipcRenderer.invoke('agent:cancel'),
        isCancelled: () => electron_1.ipcRenderer.invoke('agent:is-cancelled'),
        resetCancel: () => electron_1.ipcRenderer.invoke('agent:reset-cancel'),
    },
    // ── Mind Palace ────────────────────────────────────────────────────────────
    mindPalace: {
        initialize: () => electron_1.ipcRenderer.invoke('mind-palace:initialize'),
        storeMemory: (payload) => electron_1.ipcRenderer.invoke('mind-palace:store-memory', payload),
        search: (embedding, topK) => electron_1.ipcRenderer.invoke('mind-palace:search', embedding, topK),
        searchKeyword: (query, limit) => electron_1.ipcRenderer.invoke('mind-palace:search-keyword', query, limit),
        getMemory: (id) => electron_1.ipcRenderer.invoke('mind-palace:get-memory', id),
        loadImage: (relativePath) => electron_1.ipcRenderer.invoke('mind-palace:load-image', relativePath),
        getStats: () => electron_1.ipcRenderer.invoke('mind-palace:get-stats'),
        getRecent: (limit) => electron_1.ipcRenderer.invoke('mind-palace:get-recent', limit),
        getAllEmbeddings: () => electron_1.ipcRenderer.invoke('mind-palace:get-all-embeddings'),
        getAllMetadata: () => electron_1.ipcRenderer.invoke('mind-palace:get-all-metadata'),
    },
};
electron_1.contextBridge.exposeInMainWorld('tana', bridge);
